/**
 * Enumerable for the possible todo actions
 */
export const TODO_ACTIONS = {
  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  CHANGE_TYPE: 'CHANGE_TYPE',
  MARK_ALL_AS_DONE: 'MARK_ALL_AS_DONE',
  REMOVE_ALL_DONE: 'REMOVE_ALL_DONE',
  TOGGLE_SHOW_DONE: 'TOGGLE_SHOW_DONE',
  TOGGLE_DONE: 'TOGGLE_DONE',
  CLEAN_ERROR: 'CLEAN_ERROR',
  SET_LOADING: 'SET_LOADING',
  SET_NOTIFICATION: 'SET_NOTIFICATION',
};
